### ISSUE TITLE
【请折叠我】这吐槽我给83分，233333好了剩下的17分已给出

### ISSUE THREAD

**Issue by linesh-simplicity** [helldwellercn/helldwellercn.github.io#1]
https://github.com/helldwellercn/helldwellercn.github.io/blob/master/_posts/2015-09-09-first-blog.md

> 怒删出问题的md文件

看到这一行我的表情是这样的：

![](没找到图)

这修bug的技能我给满分！

￼￼

**Comment by helldwellercn** [comment]
哈，有问题就干掉！

**Comment by linesh-simplicity** [comment]
项目上的maven
